version: '3.8'

services:

  postgres:
    image: "postgres:17"
    container_name: "go8_postgres_e2e"
    restart: "no"
    healthcheck:
      test: pg_isready -U go8_e2e_user
    environment:
      POSTGRES_USER: go8_e2e_user
      POSTGRES_PASSWORD: go8_e2e_pass
      POSTGRES_DB: go8_e2e_db

  server:
    image: "go8/server_test"
    container_name: "go8_server_e2e"
    restart: "no"
    build:
      context: ../
      dockerfile: e2e/server.Dockerfile
    entrypoint: ["/usr/local/bin/server"]
    environment:
      - DB_DRIVER=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=go8_e2e_user
      - DB_PASS=go8_e2e_pass
      - DB_NAME=go8_e2e_db
      - DB_SSLMODE=disable
      - API_HOST=server
      - API_PORT=3080
    depends_on:
      - postgres
      - migrate

  migrate:
    image: "go8/migrate"
    container_name: "go8_migrate_e2e"
    restart: "no"
    build:
      context: ../
      dockerfile: e2e/migrate.Dockerfile
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        psql -h postgres -U go8_e2e_user -d go8_e2e_db -f /app/database/schema.sql
        psql -h postgres -U go8_e2e_user -d go8_e2e_db -f /app/database/config_schema.sql
        psql -h postgres -U go8_e2e_user -d go8_e2e_db -f /app/database/data_schema.sql
    environment:
      - PGPASSWORD=go8_e2e_pass
    depends_on:
      - postgres

  e2e:
    image: "go8/e2e"
    container_name: "go8_e2e_test"
    restart: "no"
    build:
      context: ../
      dockerfile: e2e/e2e.Dockerfile
    entrypoint: ["/usr/local/bin/end_to_end"]
    environment:
      - API_HOST=server
      - API_PORT=3080
    depends_on:
      - postgres
      - migrate
      - server
